
submit: true
job_flavour: workday

chunk_size: 1        # files per job
target_chunk_size_gb: 5.0
max_files_per_chunk: 5
max_files: -1        # -1 = all files
use_ext: true     # if true, use all nanoAOD paths in each list; otherwise only the first


output_dir: /eos/cms/store/group/phys_higgs/cmshmm/vdamante/skim_v4/
output_dir_noJetHornVeto: /eos/cms/store/group/phys_higgs/cmshmm/vdamante/skim_v4_noJetHornVeto/

# ---------------------------------------------------------
# condor configuration
# ---------------------------------------------------------

request_cpus: 1
request_memory: 4GB
request_disk: 2GB

# ---------------------------------------------------------
# optional controls
# ---------------------------------------------------------

# run only subset of datasets (optional override)
datasets_whitelist: []
  # - Muon_Run2022C
#   - Muon_Run2022D

# debug mode
dryrun: false


process_to_select:
  - Data_Muon
  - DY
  - DYto2Mu_MLL105To160
  - DYto2Mu_MLL105To160_FlashSim
  - DYto2Mu_minnlo
  - TT
  - W
  - EWK
  - EWK_Flashsim
  - EWK_2Mu2J_MLL_105to160_herwig
  - EWK_2Mu2J_MLL_105to160_herwig_Flashsim
  - EWK_2Mu2J_MLL_105to160_pythia
  - EWK_2Mu2J_MLL_105to160_pythia_Flashsim
  - SingleH
  - VV
  - VH_inclusive
  - VVV
  - ST
  - TW
  - TTX
  - TTto2L2Nu_Flashsim
  - VBFHto2Mu_M125_amcatnlo
  - VBFHto2Mu_m125_Flashsim
  - VBFHto2Mu_M125_powheg
  - GluGluHto2Mu
  - GluGluHto2Mu_amcatnlo
  - TTH_inclusive


proxy_location: /afs/cern.ch/work/v/vdamante/Hmm_newSkim/data/voms.proxy
