#!/usr/bin/env python3
"""Generate LaTeX tables for histogram selections, weights and systematics."""

from __future__ import annotations

import argparse
import re
from collections import defaultdict
from pathlib import Path
from typing import Any

import yaml


ERAS = ("Run3_2022", "Run3_2022EE", "Run3_2023", "Run3_2023BPix", "Run3_2024", "Run3_2025", "Run3_2026")
SECTIONS = ("masses_regions", "muons_selection", "jets_selection", "categories")


def load_yaml(path: Path) -> dict[str, Any]:
    with path.open(encoding="utf-8") as stream:
        data = yaml.safe_load(stream) or {}
    if not isinstance(data, dict):
        raise ValueError(f"{path}: expected a mapping")
    return data


def require(path: Path, patterns: list[str]) -> None:
    source = path.read_text(encoding="utf-8")
    missing = [pattern for pattern in patterns if re.search(pattern, source, re.DOTALL) is None]
    if missing:
        raise RuntimeError(f"workflow changed in {path}: missing {missing[0]!r}")


def validate(repo: Path) -> None:
    require(repo / "common/prepare_rdf.py", [
        r"DefineSelections\(", r"apply_custom_weights\(",
        r"GetRdfForDataset\(", r"define_shifted_jet_observables\(",
        r"finalize_histogram_dataframe\(",
    ])
    require(repo / "histograms/hist_maker.py", [
        r"prepare_rdf\(", r"prepare_region_dataframes\(", r"Histo1D\(", r"Histo2D\(",
    ])
    require(repo / "common/add_vars.py", [
        r'section_suffix_key\s*=.*?"masses_regions".*?"muons_selection".*?"jets_selection".*?"categories"',
        r"expression_template\.format\(",
    ])


def esc(value: Any) -> str:
    replacements = {"\\": r"\textbackslash{}", "&": r"\&", "%": r"\%", "$": r"\$", "#": r"\#", "_": r"\_", "{": r"\{", "}": r"\}", "~": r"\textasciitilde{}", "^": r"\textasciicircum{}"}
    return "".join(replacements.get(char, char) for char in str(value))


def compact(value: Any) -> str:
    return " ".join(str(value).split())


def longtable(lines: list[str], widths: tuple[str, ...], headers: tuple[str, ...], caption: str, label: str, rows: list[tuple[Any, ...]]) -> None:
    spec = " ".join(rf">{{\raggedright\arraybackslash}}p{{{width}\textwidth}}" for width in widths)
    ncols = len(headers)
    header = " & ".join(rf"\textbf{{{esc(item)}}}" for item in headers) + r" \\"
    lines += [rf"\begin{{longtable}}{{{spec}}}", rf"\caption{{{caption}}}\label{{{label}}} \\", r"\toprule", header, r"\midrule", r"\endfirsthead", rf"\multicolumn{{{ncols}}}{{c}}{{\tablename\ \thetable\ -- continued}} \\", r"\toprule", header, r"\midrule", r"\endhead", rf"\midrule \multicolumn{{{ncols}}}{{r}}{{Continued on next page}} \\", r"\endfoot", r"\bottomrule", r"\endlastfoot"]
    lines.extend(" & ".join(esc(cell) for cell in row) + r" \\" for row in rows)
    lines += [r"\end{longtable}", ""]


def render(repo: Path) -> str:
    validate(repo)
    configs = {
        era: {
            "main": load_yaml(repo / "config" / era / "maincfg.yaml"),
            "sel": load_yaml(repo / "config" / era / "selections.yaml"),
            "syst": load_yaml(repo / "config" / era / "systematics.yaml"),
        }
        for era in ERAS
    }
    lines = ["% Generated by sync/python/collect_histogram_workflow.py; do not edit manually."]
    workflow_rows = [
        (1, "Validated skim inputs", "Read all validated Events trees; MC normalization denominators come from dataset-wide skim reports/manifest metadata", "No new object calibration; consumes corrected and shifted skim branches"),
        (2, "Optional additional cut", "If --additional-cuts is supplied, apply it directly with RDataFrame.Filter", "User-defined event filter, before derived observables and weights"),
        (3, "Weights and observables", "Build central/shifted weights, trigger SF, PDF and QCD-scale weights; define selected-jet, VBF, dimuon, soft-activity and requested DNN observables", "Uses corrections stored by the skim"),
        (4, "Shifted jet observables", "For requested JER/JES suffixes, rebuild selected-jet and VBF observables; fail if required skim columns are absent", "Shape-systematic preparation"),
        (5, "Reco/gen jet matching", "For eligible MC, define jet matching and optional DY/EWK exclusive jet-component categories", "MC only; optional component workflow"),
        (6, "Histogram selections", "Define/redefine every masses_regions, muons_selection, jets_selection and categories expression from selections.yaml, including requested shape suffixes", "Definitions first; no rejection yet"),
        (7, "DY normalization/reweights", "Apply amcatnlo normalization and optional DY pT(ll) and Njets reweights to all target weight columns", "MC DY only; weights, not filters"),
        (8, "Mass-region filter", "Filter on each requested stored mass-region column (default: mass_inclusive, Z_sideband, Signal_Fit)", "First histogram-level event selection"),
        (9, "Sideband DNN", "For DNN_NNOutput in Z/H sidebands, remap m_mumu into the training window and reevaluate the dedicated DNN payload", "Only requested DNN sideband histograms"),
        (10, "Category filter", "Within each mass region, filter each requested stored category (default: baseline, ggF, VBF)", "Second histogram-level event selection"),
        (11, "Systematic routing", "Choose shape-shifted variable/selection columns or weight-only variations; data are forced to Central", "JER/JES/Muon scale/resolution shapes; PU/muon/PDF/QCD weights"),
        (12, "Histogram booking", "Book configured 1D/2D models with the selected variable and weight; missing shifted variables produce empty templates", "Output organized by mass region and category"),
        (13, "Output postprocessing", "Build QCD scale envelopes, PDF treatment and optional split component files in the dataset output", "Final histogram products"),
    ]
    longtable(lines, ("0.04", "0.17", "0.46", "0.27"), ("Step", "Operation", "Action", "Selection/correction status"), "Histogram-production workflow in execution order.", "tab:hist-workflow", workflow_rows)

    grouped: dict[tuple[str, str, str, bool], list[str]] = defaultdict(list)
    for era, group in configs.items():
        for section in SECTIONS:
            for name, content in group["sel"].get(section, {}).items():
                if isinstance(content, dict):
                    expression = compact(content.get("expression", ""))
                    store = bool(content.get("store", True))
                else:
                    expression, store = compact(content), True
                grouped[(section, name, expression, store)].append(era.removeprefix("Run3_"))
    selection_rows = []
    for (section, name, expression, store), eras in grouped.items():
        booking_use = "filter candidate" if section in {"masses_regions", "categories"} and store else "definition/dependency"
        selection_rows.append((section, name, expression, "yes" if store else "no", ", ".join(eras), booking_use))
    longtable(lines, ("0.11", "0.13", "0.42", "0.05", "0.13", "0.11"), ("YAML section", "Name", "Expression", "Store", "Eras", "Histogram use"), "All histogram-level selection definitions. Rows are merged when identical across eras.", "tab:hist-selections", selection_rows)

    syst_grouped: dict[tuple[str, str, str, str, str], list[str]] = defaultdict(list)
    for era, group in configs.items():
        syst = group["syst"]
        for name, info in syst.get("systematics", {}).items():
            syst_grouped[("shape", name, info.get("muon_suffix", ""), info.get("jet_suffix", ""), info.get("weight", ""))].append(era.removeprefix("Run3_"))
        for name, info in syst.get("weights", {}).items():
            expression = compact(info.get("expression", info.get("relative_expression", "derived/envelope")))
            syst_grouped[("weight", name, "", expression, info.get("weight", ""))].append(era.removeprefix("Run3_"))
    syst_rows = [(kind, name, mu, jet_or_expr, weight, ", ".join(eras)) for (kind, name, mu, jet_or_expr, weight), eras in syst_grouped.items()]
    longtable(lines, ("0.08", "0.14", "0.12", "0.41", "0.13", "0.08"), ("Type", "Systematic", "Muon suffix", "Jet suffix / weight expression", "Weight column", "Eras"), "Shape and weight systematics configured for histogram production.", "tab:hist-systematics", syst_rows)

    central_rows = []
    for era, group in configs.items():
        expression = compact(group["syst"].get("weights", {}).get("Central", {}).get("expression", "data: unit/central weight"))
        central_rows.append((era, expression))
    longtable(lines, ("0.13", "0.80"), ("Era", "Central MC weight expression"), "Central event weights used to fill MC histograms.", "tab:hist-central-weights", central_rows)
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()
    repo = Path(__file__).resolve().parents[2]
    output = args.output or repo / "sync/latex/histogram_workflow_table.tex"
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render(repo), encoding="utf-8")
    print(f"Wrote {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
